services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    #    volumes:
      #  - inventory_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: inventory_db

#volumes:
  #  inventory_volume:
